# common params
depth_registration: false
enable_point_cloud: true
enable_colored_point_cloud: false
device_preset: "High Accuracy"
time_domain: "global" # global, device, system
enable_sync_host_time: true
frames_per_trigger: 1
log_level: "warning"
enable_laser: false

interleave_frame_enable: true
interleave_skip_enable: true

# color params
enable_color: true
color_width: 1280
color_height: 800
color_fps: 30
color_format: "MJPG"
enable_color_auto_exposure: true
color_exposure: 50 # 5ms
color_gain: -1 # -1 default
color_qos: "sensor_data"

# depth params
depth_width: 1280
depth_height: 800
depth_fps: 30
depth_format: "Y16"
depth_qos: "sensor_data"

# ir exposure
enable_ir_auto_exposure: true
ir_exposure: 5000
ir_gain: 40

#left ir params
enable_left_ir: true
left_ir_width: 1280
left_ir_height: 800
left_ir_fps: 30
left_ir_format: "Y8"
left_ir_qos: "sensor_data"

#right ir params
enable_right_ir: true
right_ir_width: 1280
right_ir_height: 800
right_ir_fps: 30
right_ir_format: "Y8"
right_ir_qos: "sensor_data"
