# common params
depth_registration: false
enable_d2c_viewer: false
enable_point_cloud: false
enable_colored_point_cloud: false
enable_ldp: false
device_preset: "Default"
enable_laser: true

# enable_laser: true
interleave_ae_mode: "laser"
interleave_frame_enable: false
interleave_skip_enable: false
interleave_skip_index: 1
time_domain: "global" # global, device, system
enable_sync_host_time: true

trigger_out_enabled: false
frames_per_trigger: 0
software_trigger_period: 0


# color params
enable_color: true
color_width: 0
color_height: 0
color_fps: 0
color_format: "ANY"
enable_color_auto_exposure: true
color_exposure: 30 # 3ms
color_gain: 16 # -1 default

# depth params
enable_depth: true
depth_width: 0
depth_height: 0
depth_fps: 0
depth_format: "ANY"


#left ir params
enable_left_ir: false
left_ir_width: 0
left_ir_height: 0
left_ir_fps: 0
left_ir_format: "ANY"
enable_ir_auto_exposure: true
ir_exposure: 3000 # 3ms
ir_gain: 16 # -1 default

#right ir params
enable_right_ir: false
right_ir_width: 0
right_ir_height: 0
right_ir_fps: 0
right_ir_format: "ANY"

#ir params except 330
# enable_ir: true
# ir_width: 0
# ir_height: 0
# ir_fps: 0
# ir_format: "ANY"


